version: '3.8'

services:
  webapp:
    build: ./webapp
    ports:
      - 5000:5000
  rest-api:
    build: ./api
    ports:
      - 5001:5000
    environment:
      MONGO_PASS: "${MONGO_PASS}"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017 # MongoDB listens on port 27017 by default
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"