name: Run API tests

on:
  push:
    branches:
      - $default-branch
    pull_request:
      - $default-branch

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Build container images
      run: |
        docker-compose build
    - name: Set up database
      run: |
        docker-compose up -d mongo
    - name: Run tests
      run: |
        docker-compose run --entrypoint pytest rest-api